[package]
name = "parrot-updater"
version = "2.0.0"
edition = "2024"
authors = ["Dario 'danterolle' Camonita <danterolle@parrotsec.org>"]

[dependencies]
gtk4 = "0.10.3"
chrono = "0.4"
async-channel = "2.5.0"
glib = "0.21.5"
notify-rust = "4.11.7"